---
- name: Deploy Backend on Kubernetes
  hosts: all
  tasks:
    - name: Create web-app namespace
      kubernetes.core.k8s:
        name: web-app
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy Backend Service and Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          # --- ส่วนของ Deployment ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend
            namespace: web-app
          spec:
            replicas: 1
            strategy:
              type: Recreate  # เพิ่มส่วนนี้เพื่อให้ SQLite ไม่โดน Lock ตอน Update
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                - name: backend
                  # ใช้ตัวแปรที่ส่งมาจาก Jenkinsfile
                  image: "{{ docker_user }}/server-backend:{{ version }}"
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 8080
                  env:
                    - name: DB_PATH
                      value: "/app/data/app.db"
                  volumeMounts:
                    - name: sqlite-storage
                      mountPath: /app/data
                volumes:
                  - name: sqlite-storage
                    persistentVolumeClaim:
                      claimName: sqlite-pvc

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition:
          # --- ส่วนของ Service ---
          apiVersion: v1
          kind: Service
          metadata:
            name: backend-service
            namespace: web-app
          spec:
            selector:
              app: backend
            ports:
            - port: 8080
              targetPort: 8080