---
- name: Master Deploy Playbook Setup Namespace
  hosts: all
  tasks:
    - name: 1. Ensure Namespace exists
      shell: kubectl create namespace web-app --dry-run=client -o yaml | kubectl apply -f -

- import_playbook: k8s-manifests/sqlite-pvc.yml
- import_playbook: k8s-manifests/deploy_backend.yml
- import_playbook: k8s-manifests/deploy_frontend.yml